In [43]:


import pandas as pd

LUAD_amp_df = pd.read_csv('LUAD_table_amp.conf_95.txt', sep='\t')
LUAD_amp_df['peak_id'] = 'chr' + LUAD_amp_df.chromosome.astype(str) + ':' + LUAD_amp_df.peak_start.astype(str) + '-' + LUAD_amp_df.peak_end.astype(str)
LUAD_amp_df.index = LUAD_amp_df['peak_id']
LUAD_del_df = pd.read_csv('LUAD_table_del.conf_95.txt', sep='\t')
LUAD_del_df['peak_id'] = 'chr' + LUAD_del_df.chromosome.astype(str) + ':' + LUAD_del_df.peak_start.astype(str) + '-' + LUAD_del_df.peak_end.astype(str)
LUAD_del_df.index = LUAD_del_df['peak_id']

LUSC_amp_df = pd.read_csv('LUSC_table_amp.conf_95.txt', sep='\t')
LUSC_amp_df['peak_id'] = 'chr' + LUSC_amp_df.chromosome.astype(str) + ':' + LUSC_amp_df.peak_start.astype(str) + '-' + LUSC_amp_df.peak_end.astype(str)
LUSC_amp_df.index = LUSC_amp_df['peak_id']
LUSC_del_df = pd.read_csv('LUSC_table_del.conf_95.txt', sep='\t')
LUSC_del_df['peak_id'] = 'chr' + LUSC_del_df.chromosome.astype(str) + ':' + LUSC_del_df.peak_start.astype(str) + '-' + LUSC_del_df.peak_end.astype(str)
LUSC_del_df.index = LUSC_del_df['peak_id']

SCLC_amp_df = pd.read_csv('SCLC_table_amp.conf_95.txt', sep='\t')
SCLC_amp_df['peak_id'] = 'chr' + SCLC_amp_df.chromosome.astype(str) + ':' + SCLC_amp_df.peak_start.astype(str) + '-' + SCLC_amp_df.peak_end.astype(str)
SCLC_amp_df.index = SCLC_amp_df['peak_id']
SCLC_del_df = pd.read_csv('SCLC_table_del.conf_95.txt', sep='\t')
SCLC_del_df['peak_id'] = 'chr' + SCLC_del_df.chromosome.astype(str) + ':' + SCLC_del_df.peak_start.astype(str) + '-' + SCLC_del_df.peak_end.astype(str)
SCLC_del_df.index = SCLC_del_df['peak_id']

SCLC_del_df

,index,chromosome,region_start,region_end,peak_start,peak_end,enlarged_peak_start,enlarged_peak_end,n_genes_in_region,genes_in_region,n_genes_in_peak,genes_in_peak,n_genes_on_chip,genes_on_chip,top 3,peak_id
peak_id,,,,,,,,,,,,,,,,
chr4:153460000-188610000,1,4,153560000,153570000,153460000,188610000,153420000,189658465,166,"hsa-mir-1979,AGA,SLC25A4,CASP3,CLCN3,CPE,CTSO,...",165,"hsa-mir-1979,AGA,SLC25A4,CASP3,CLCN3,CPE,CTSO,...",NaN,NaN,NaN,chr4:153460000-188610000
chr22:15520001-20500001,2,22,15530001,15540001,15520001,20500001,11960001,20500001,95,"ARVCF,ATP6V1E1,BID,COMT,GGT3P,GP1BB,GSC2,SEPT5...",95,"ARVCF,ATP6V1E1,BID,COMT,GGT3P,GP1BB,GSC2,SEPT5...",NaN,NaN,NaN,chr22:15520001-20500001

In [6]:
tree_df = pd.read_excel('subclone_tree_edge.xlsx')
print(tree_df)

cnv_df = pd.read_excel('subclone_cnv.xlsx', index_col=0)
cnv_df.columns = [ '{}:{}-{}'.format(*x.split('.')) for x in cnv_df.columns]
cnv_df

    Type   Sample      Source      Target
0   LUAD  LUAD01T   LUAD01T_N   LUAD01T_D
1   LUAD  LUAD01T   LUAD01T_N  LUAD01T_LX
2   LUAD  LUAD02T   LUAD02T_N  LUAD02T_LX
3   LUAD  LUAD03T   LUAD03T_N   LUAD03T_A
4   LUAD  LUAD03T   LUAD03T_N   LUAD03T_D
5   LUAD  LUAD03T   LUAD03T_N   LUAD03T_L
6   LUAD  LUAD03T   LUAD03T_N  LUAD03T_LX
7   LUAD  LUAD04T   LUAD04T_N  LUAD04T_A1
8   LUAD  LUAD04T   LUAD04T_N   LUAD04T_D
9   LUAD  LUAD04T   LUAD04T_N  LUAD04T_LX
10  LUAD  LUAD05T   LUAD05T_N   LUAD05T_A
11  LUAD  LUAD05T   LUAD05T_N  LUAD05T_A1
12  LUAD  LUAD05T   LUAD05T_N  LUAD05T_LX
13  LUAD  LUAD05T  LUAD05T_A1  LUAD05T_A2
14  LUAD  LUAD05T  LUAD05T_A1  LUAD05T_A3
15  LUAD  LUAD06T   LUAD06T_N  LUAD06T_A1
16  LUAD  LUAD06T   LUAD06T_N  LUAD06T_A3
17  LUAD  LUAD06T   LUAD06T_N  LUAD06T_LX
18  LUAD  LUAD06T  LUAD06T_A1  LUAD06T_A2
19  LUAD  LUAD07T   LUAD07T_N  LUAD07T_A2
20  LUAD  LUAD07T   LUAD07T_N  LUAD07T_LX
21  LUAD  LUAD07T  LUAD07T_LX  LUAD07T_A2
22  LUAD  LUAD07T  LUAD07T_LX   LUAD07T_L
23  LUSC  LUSC01T   LUSC01T_N  LUSC01T_LX
24  LUSC  LUSC02T   LUSC02T_N  LUSC02T_A1
25  LUSC  LUSC02T   LUSC02T_N   LUSC02T_D
26  LUSC  LUSC04T   LUSC04T_N  LUSC04T_A1
27  LUSC  LUSC04T   LUSC04T_N  LUSC04T_LX
28  LUSC  LUSC05T   LUSC05T_N   LUSC05T_A
29  LUSC  LUSC05T   LUSC05T_N  LUSC05T_L1
30  LUSC  LUSC05T   LUSC05T_N  LUSC05T_LX
31  LUSC  LUSC06T   LUSC06T_N   LUSC06T_A
32  LUSC  LUSC06T   LUSC06T_N  LUSC06T_LX
33  LUSC  LUSC07T   LUSC07T_N  LUSC07T_A1
34  LUSC  LUSC07T   LUSC07T_N   LUSC07T_D
35  LUSC  LUSC07T   LUSC07T_N  LUSC07T_LX
36  LUSC  LUSC07T  LUSC07T_A1  LUSC07T_A3
37  LUSC  LUSC08T   LUSC08T_N  LUSC08T_A1
38  LUSC  LUSC08T   LUSC08T_N  LUSC08T_A2
39  LUSC  LUSC08T   LUSC08T_N  LUSC08T_LX
40  LUSC  LUSC08T  LUSC08T_A2  LUSC08T_A3
41  LUSC  LUSC08T  LUSC08T_A3  LUSC08T_A4
42  SCLC  SCLC01T   SCLC01T_N  SCLC01T_A1
43  SCLC  SCLC01T   SCLC01T_N  SCLC01T_LX
44  SCLC  SCLC01T  SCLC01T_A1  SCLC01T_A2
45  SCLC  SCLC01T  SCLC01T_A1  SCLC01T_A3
46  SCLC  SCLC02T   SCLC02T_N   SCLC02T_A
47  SCLC  SCLC02T   SCLC02T_N  SCLC02T_L1
48  SCLC  SCLC02T   SCLC02T_N  SCLC02T_LX

,chr1:1-5120000,chr1:5120001-10240000,chr1:10240001-15360000,chr1:15360001-20480000,chr1:20480001-25600000,chr1:25600001-30720000,chr1:30720001-35840000,chr1:35840001-40960000,chr1:40960001-46080000,chr1:46080001-51200000,...,chrY:10240001-15360000,chrY:15360001-20480000,chrY:20480001-25600000,chrY:25600001-30720000,chrY:30720001-35840000,chrY:35840001-40960000,chrY:40960001-46080000,chrY:46080001-51200000,chrY:51200001-56320000,chrY:56320001-57227415
Subclone,,,,,,,,,,,,,,,,,,,,,
LUAD01T_A,4.847656,5.000000,5.000000,4.308594,4.000000,4.000000,4.339844,5.738281,4.398438,3.000000,...,0.195312,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LUAD01T_D,1.974447,2.041667,2.052897,2.027995,2.001302,1.989258,1.993164,1.995117,1.948568,2.006348,...,0.270345,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LUAD01T_L,1.000000,1.050781,1.000000,1.109375,1.000000,1.000000,1.121094,1.078125,0.949219,0.828125,...,0.058594,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LUAD01T_LX,2.023438,2.000000,2.074219,2.062500,1.988281,2.000000,2.000000,2.000000,2.000000,2.000000,...,0.269531,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LUAD02T_A,4.988281,5.910156,5.914062,5.082031,4.000000,3.828125,4.000000,4.000000,3.937500,4.429688,...,1.839844,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SCLC01T_LX,2.007812,2.000000,2.000000,2.058594,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,...,1.402344,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SCLC02T_A,3.490234,3.976562,3.947266,4.166016,4.000000,3.951172,3.947266,4.000000,4.000000,4.300781,...,1.611328,0.732422,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SCLC02T_L1,1.792969,1.972656,1.988281,2.046875,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,...,1.140625,0.464844,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SCLC02T_L2,0.031250,0.000000,0.230469,0.066406,0.000000,0.039062,0.023438,0.230469,0.394531,0.078125,...,0.062500,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SCLC02T_LX,1.870206,1.965021,2.000710,2.096946,1.984020,1.988104,1.971413,2.012784,2.011541,2.009943,...,1.220348,0.954545,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
with open('tree_edge_focal_cnv.csv', 'w') as f:
    f.write('Type,Sample,Source,Target,Amp/Del,Peak,CN_Change,Gene\n')
    
    for i, row in tree_df.iterrows():
        #if i > 2: break
        cancer_type = row['Type']
        if cancer_type == 'LUAD':
            amp_df = LUAD_amp_df
            del_df = LUAD_del_df
        if cancer_type == 'LUSC':
            amp_df = LUSC_amp_df
            del_df = LUSC_del_df
        if cancer_type == 'SCLC':
            amp_df = SCLC_amp_df
            del_df = SCLC_del_df            
    
        source, target = row['Source'], row['Target']
    
        if source.endswith('_N'):
            source_cn = 2
        else:
            source_cn = cnv_df.loc[source]
        target_cn = cnv_df.loc[target]
        change = target_cn - source_cn
    
        delta = 1
        amp_cn = change[change >= delta]
        del_cn = change[change <= -delta]

        amp_bins = set(amp_cn.index) & set(amp_df.peak_id)
        del_bins = set(del_cn.index) & set(del_df.peak_id)

        for amp_bin in amp_bins:
            for gene in amp_df.loc[amp_bin].genes_in_peak.split(','):
                if gene:
                    f.write(','.join(map(str, [row['Type'], row['Sample'], source, target, 'Amp', amp_bin, amp_cn.loc[amp_bin], gene])) + '\n')
            
        for del_bin in del_bins:
            for gene in del_df.loc[del_bin].genes_in_peak.split(','):
                if gene:
                    f.write(','.join(map(str, [row['Type'], row['Sample'], source, target, 'Del', del_bin, del_cn.loc[del_bin], gene])) + '\n')