In [6]:


import pandas as pd

LUAD_amp_df = pd.read_csv('LUAD_table_amp.conf_95.txt', sep='\t')
LUAD_amp_df['peak_id'] = 'chr' + LUAD_amp_df.chromosome.astype(str) + ':' + LUAD_amp_df.peak_start.astype(str) + '-' + LUAD_amp_df.peak_end.astype(str)
LUAD_amp_df.index = LUAD_amp_df['peak_id']
LUAD_del_df = pd.read_csv('LUAD_table_del.conf_95.txt', sep='\t')
LUAD_del_df['peak_id'] = 'chr' + LUAD_del_df.chromosome.astype(str) + ':' + LUAD_del_df.peak_start.astype(str) + '-' + LUAD_del_df.peak_end.astype(str)
LUAD_del_df.index = LUAD_del_df['peak_id']

LUSC_amp_df = pd.read_csv('LUSC_table_amp.conf_95.txt', sep='\t')
LUSC_amp_df['peak_id'] = 'chr' + LUSC_amp_df.chromosome.astype(str) + ':' + LUSC_amp_df.peak_start.astype(str) + '-' + LUSC_amp_df.peak_end.astype(str)
LUSC_amp_df.index = LUSC_amp_df['peak_id']
LUSC_del_df = pd.read_csv('LUSC_table_del.conf_95.txt', sep='\t')
LUSC_del_df['peak_id'] = 'chr' + LUSC_del_df.chromosome.astype(str) + ':' + LUSC_del_df.peak_start.astype(str) + '-' + LUSC_del_df.peak_end.astype(str)
LUSC_del_df.index = LUSC_del_df['peak_id']

SCLC_amp_df = pd.read_csv('SCLC_table_amp.conf_95.txt', sep='\t')
SCLC_amp_df['peak_id'] = 'chr' + SCLC_amp_df.chromosome.astype(str) + ':' + SCLC_amp_df.peak_start.astype(str) + '-' + SCLC_amp_df.peak_end.astype(str)
SCLC_amp_df.index = SCLC_amp_df['peak_id']
SCLC_del_df = pd.read_csv('SCLC_table_del.conf_95.txt', sep='\t')
SCLC_del_df['peak_id'] = 'chr' + SCLC_del_df.chromosome.astype(str) + ':' + SCLC_del_df.peak_start.astype(str) + '-' + SCLC_del_df.peak_end.astype(str)
SCLC_del_df.index = SCLC_del_df['peak_id']

LUAD_del_df

,index,chromosome,region_start,region_end,peak_start,peak_end,enlarged_peak_start,enlarged_peak_end,n_genes_in_region,genes_in_region,n_genes_in_peak,genes_in_peak,n_genes_on_chip,genes_on_chip,top 3,peak_id
peak_id,,,,,,,,,,,,,,,,
chr1:117860001-121580000,1,1,117760001,148500001,117860001,121580000,117630000,143390001,36,"FCGR1B,HMGCS2,HSD3B1,HSD3B2,NOTCH2,TBX15,SEC22...",36,"FCGR1B,HMGCS2,HSD3B1,HSD3B2,NOTCH2,TBX15,SEC22...",NaN,NaN,NaN,chr1:117860001-121580000
chr1:143390001-148460000,2,1,117760001,148500001,143390001,148460000,121580000,148480001,76,"BCL9,DRD5P2,FMO5,GJA5,GJA8,PDZK1,PRKAB2,RNU1-4...",75,"BCL9,DRD5P2,FMO5,GJA5,GJA8,PDZK1,PRKAB2,RNU1-4...",NaN,NaN,NaN,chr1:143390001-148460000
chr2:87030000-91950000,3,2,87040001,97300001,87030000,91950000,87020000,97280001,70,"ADRA2B,DUSP2,FABP1,MAL,PLGLB2,PLGLB1,ZNF2,CIAO...",26,"FABP1,PLGLB2,PLGLB1,EIF2AK3,RPIA,KRCC1,THNSL2,...",NaN,NaN,NaN,chr2:87030000-91950000
chr5:50390000-50980000,4,5,46080001,51220001,50390000,50980000,45700000,51370001,3,"PARP8,EMB,LOC100287592,",3,"PARP8,EMB,LOC100287592,",NaN,NaN,NaN,chr5:50390000-50980000
chr7:56420001-76630000,5,7,56320001,66580001,56420001,76630000,56120000,76980001,147,"ASL,CLDN4,CLDN3,ELN,ERV3-1,GTF2I,GTF2IP1,GUSB,...",146,"ASL,CLDN4,CLDN3,ELN,ERV3-1,GTF2I,GTF2IP1,GUSB,...",NaN,NaN,NaN,chr7:56420001-76630000
chr9:138210000-138249671,6,9,133120001,138394717,138210000,138249671,138200000,138394717,2,"FAM157B,LOC101928932,",1,"FAM157B,",NaN,NaN,NaN,chr9:138210000-138249671
chr9:40990001-66170000,7,9,40960001,81940001,40990001,66170000,40930000,66900001,48,"SPATA31A7,ANKRD20A1,CBWD5,LOC286297,FOXD4L4,AQ...",47,"SPATA31A7,ANKRD20A1,CBWD5,LOC286297,FOXD4L4,AQ...",NaN,NaN,NaN,chr9:40990001-66170000
chr9:66900001-81920000,8,9,40960001,81940001,66900001,81920000,66170000,81920001,76,"ALDH1A1,ANXA1,APBA1,KLF9,FXN,GCNT1,GNAQ,PCSK5,...",76,"ALDH1A1,ANXA1,APBA1,KLF9,FXN,GCNT1,GNAQ,PCSK5,...",NaN,NaN,NaN,chr9:66900001-81920000
chr11:54600000-56320000,9,11,51200001,56340001,54600000,56320000,50430000,56340001,37,"OR5I1,OR5L2,TRIM48,OR8J3,OR4P4,OR4C15,OR4A5,OR...",36,"OR5I1,OR5L2,TRIM48,OR8J3,OR4P4,OR4C15,OR4A5,OR...",NaN,NaN,NaN,chr11:54600000-56320000
chr15:40970001-45700000,10,15,40960001,46100001,40970001,45700000,40960000,47180001,96,"B2M,CAPN3,CKMT1B,EPB42,GANC,GATM,PDIA3,ITPKA,L...",94,"B2M,CAPN3,CKMT1B,EPB42,GANC,GATM,PDIA3,ITPKA,L...",NaN,NaN,NaN,chr15:40970001-45700000
chr16:15360001-20490001,11,16,15360001,20500001,15360001,20490001,15160000,30740001,231,"ALDOA,AQP8,ABCC6,ATP2A1,CD19,CDR2,CLN3,CRYM,SE...",57,"ABCC6,GP2,ABCC1,MYH11,RPS15A,UMOD,NPIPA1,KIAA0...",NaN,NaN,NaN,chr16:15360001-20490001
chr19:60001-5160001,12,19,1,5140001,60001,5160001,1,10250001,342,"hsa-mir-220b,AES,AMH,ATP5D,AZU1,HCN2,BSG,C3,CA...",190,"AES,AMH,ATP5D,AZU1,HCN2,BSG,CDC34,CIRBP,CNN2,C...",NaN,NaN,NaN,chr19:60001-5160001

In [3]:
tree_df = pd.read_excel('subclone_tree_edge.xlsx')
print(tree_df)

cnv_df = pd.read_excel('subclone_cnv.xlsx', index_col=0)
cnv_df.columns = [ '{}:{}-{}'.format(*x.split('.')) for x in cnv_df.columns]
cnv_df

    Type   Sample      Source      Target
0   LUAD  LUAD01T   LUAD01T_N   LUAD01T_D
1   LUAD  LUAD01T   LUAD01T_N  LUAD01T_LX
2   LUAD  LUAD02T   LUAD02T_N  LUAD02T_LX
3   LUAD  LUAD03T   LUAD03T_N   LUAD03T_A
4   LUAD  LUAD03T   LUAD03T_N   LUAD03T_D
5   LUAD  LUAD03T   LUAD03T_N   LUAD03T_L
6   LUAD  LUAD03T   LUAD03T_N  LUAD03T_LX
7   LUAD  LUAD04T   LUAD04T_N  LUAD04T_A1
8   LUAD  LUAD04T   LUAD04T_N   LUAD04T_D
9   LUAD  LUAD04T   LUAD04T_N  LUAD04T_LX
10  LUAD  LUAD05T   LUAD05T_N   LUAD05T_A
11  LUAD  LUAD05T   LUAD05T_N  LUAD05T_A1
12  LUAD  LUAD05T   LUAD05T_N  LUAD05T_LX
13  LUAD  LUAD05T  LUAD05T_A1  LUAD05T_A2
14  LUAD  LUAD05T  LUAD05T_A1  LUAD05T_A3
15  LUAD  LUAD06T   LUAD06T_N  LUAD06T_A1
16  LUAD  LUAD06T   LUAD06T_N  LUAD06T_A3
17  LUAD  LUAD06T   LUAD06T_N  LUAD06T_LX
18  LUAD  LUAD06T  LUAD06T_A1  LUAD06T_A2
19  LUAD  LUAD07T   LUAD07T_N  LUAD07T_A2
20  LUAD  LUAD07T   LUAD07T_N  LUAD07T_LX
21  LUAD  LUAD07T  LUAD07T_LX  LUAD07T_A2
22  LUAD  LUAD07T  LUAD07T_LX   LUAD07T_L
23  LUSC  LUSC01T   LUSC01T_N  LUSC01T_LX
24  LUSC  LUSC02T   LUSC02T_N  LUSC02T_A1
25  LUSC  LUSC02T   LUSC02T_N   LUSC02T_D
26  LUSC  LUSC04T   LUSC04T_N  LUSC04T_A1
27  LUSC  LUSC04T   LUSC04T_N  LUSC04T_LX
28  LUSC  LUSC05T   LUSC05T_N   LUSC05T_A
29  LUSC  LUSC05T   LUSC05T_N  LUSC05T_L1
30  LUSC  LUSC05T   LUSC05T_N  LUSC05T_LX
31  LUSC  LUSC06T   LUSC06T_N   LUSC06T_A
32  LUSC  LUSC06T   LUSC06T_N  LUSC06T_LX
33  LUSC  LUSC07T   LUSC07T_N  LUSC07T_A1
34  LUSC  LUSC07T   LUSC07T_N   LUSC07T_D
35  LUSC  LUSC07T   LUSC07T_N  LUSC07T_LX
36  LUSC  LUSC07T  LUSC07T_A1  LUSC07T_A3
37  LUSC  LUSC08T   LUSC08T_N  LUSC08T_A1
38  LUSC  LUSC08T   LUSC08T_N  LUSC08T_A2
39  LUSC  LUSC08T   LUSC08T_N  LUSC08T_LX
40  LUSC  LUSC08T  LUSC08T_A2  LUSC08T_A3
41  LUSC  LUSC08T  LUSC08T_A3  LUSC08T_A4
42  SCLC  SCLC01T   SCLC01T_N  SCLC01T_A1
43  SCLC  SCLC01T   SCLC01T_N  SCLC01T_LX
44  SCLC  SCLC01T  SCLC01T_A1  SCLC01T_A2
45  SCLC  SCLC01T  SCLC01T_A1  SCLC01T_A3
46  SCLC  SCLC02T   SCLC02T_N   SCLC02T_A
47  SCLC  SCLC02T   SCLC02T_N  SCLC02T_L1
48  SCLC  SCLC02T   SCLC02T_N  SCLC02T_LX

,chr1:1-5120000,chr1:5120001-10240000,chr1:10240001-15360000,chr1:15360001-20480000,chr1:20480001-25600000,chr1:25600001-30720000,chr1:30720001-35840000,chr1:35840001-40960000,chr1:40960001-46080000,chr1:46080001-51200000,...,chrY:10240001-15360000,chrY:15360001-20480000,chrY:20480001-25600000,chrY:25600001-30720000,chrY:30720001-35840000,chrY:35840001-40960000,chrY:40960001-46080000,chrY:46080001-51200000,chrY:51200001-56320000,chrY:56320001-57227415
Subclone,,,,,,,,,,,,,,,,,,,,,
LUAD01T_A,4.847656,5.000000,5.000000,4.308594,4.000000,4.000000,4.339844,5.738281,4.398438,3.000000,...,0.195312,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LUAD01T_D,1.974447,2.041667,2.052897,2.027995,2.001302,1.989258,1.993164,1.995117,1.948568,2.006348,...,0.270345,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LUAD01T_L,1.000000,1.050781,1.000000,1.109375,1.000000,1.000000,1.121094,1.078125,0.949219,0.828125,...,0.058594,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LUAD01T_LX,2.023438,2.000000,2.074219,2.062500,1.988281,2.000000,2.000000,2.000000,2.000000,2.000000,...,0.269531,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LUAD02T_A,4.988281,5.910156,5.914062,5.082031,4.000000,3.828125,4.000000,4.000000,3.937500,4.429688,...,1.839844,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SCLC01T_LX,2.007812,2.000000,2.000000,2.058594,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,...,1.402344,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SCLC02T_A,3.490234,3.976562,3.947266,4.166016,4.000000,3.951172,3.947266,4.000000,4.000000,4.300781,...,1.611328,0.732422,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SCLC02T_L1,1.792969,1.972656,1.988281,2.046875,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,...,1.140625,0.464844,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SCLC02T_L2,0.031250,0.000000,0.230469,0.066406,0.000000,0.039062,0.023438,0.230469,0.394531,0.078125,...,0.062500,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SCLC02T_LX,1.870206,1.965021,2.000710,2.096946,1.984020,1.988104,1.971413,2.012784,2.011541,2.009943,...,1.220348,0.954545,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
with open('tree_edge_focal_cnv.csv', 'w') as f:
    f.write('Type,Sample,Source,Target,Amp/Del,Peak,CN_Change,Gene\n')
    
    for i, row in tree_df.iterrows():
        #if i > 2: break
        cancer_type = row['Type']
        if cancer_type == 'LUAD':
            amp_df = LUAD_amp_df
            del_df = LUAD_del_df
        if cancer_type == 'LUSC':
            amp_df = LUSC_amp_df
            del_df = LUSC_del_df
        if cancer_type == 'SCLC':
            amp_df = SCLC_amp_df
            del_df = SCLC_del_df            
    
        source, target = row['Source'], row['Target']
    
        if source.endswith('_N'):
            source_cn = 2
        else:
            source_cn = cnv_df.loc[source]
        target_cn = cnv_df.loc[target]
        change = target_cn - source_cn
    
        amp_cn = change[change >= 1]
        del_cn = change[(change <= -0.5) & (target_cn < 2)]

        amp_bins = set(amp_cn.index) & set(amp_df.peak_id)
        del_bins = set(del_cn.index) & set(del_df.peak_id)

        for amp_bin in amp_bins:
            for gene in amp_df.loc[amp_bin].genes_in_peak.split(','):
                if gene:
                    f.write(','.join(map(str, [row['Type'], row['Sample'], source, target, 'Amp', amp_bin, amp_cn.loc[amp_bin], gene])) + '\n')
            
        for del_bin in del_bins:
            for gene in del_df.loc[del_bin].genes_in_peak.split(','):
                if gene:
                    f.write(','.join(map(str, [row['Type'], row['Sample'], source, target, 'Del', del_bin, del_cn.loc[del_bin], gene])) + '\n')

In [18]:
with open('tree_edge_cnv.csv', 'w') as f:
    f.write('Type,Sample,Source,Target,Amp/Del,Peak,CN_Change\n')
    
    for i, row in tree_df.iterrows():
        #if i > 2: break
        cancer_type = row['Type']
        if cancer_type == 'LUAD':
            amp_df = LUAD_amp_df
            del_df = LUAD_del_df
        if cancer_type == 'LUSC':
            amp_df = LUSC_amp_df
            del_df = LUSC_del_df
        if cancer_type == 'SCLC':
            amp_df = SCLC_amp_df
            del_df = SCLC_del_df            
    
        source, target = row['Source'], row['Target']
    
        if source.endswith('_N'):
            source_cn = 2
        else:
            source_cn = cnv_df.loc[source]
        target_cn = cnv_df.loc[target]
        change = target_cn - source_cn
    
        amp_cn = change[change >= 1]
        del_cn = change[(change <= -0.5) & (target_cn < 2)]

        amp_bins = set(amp_cn.index)
        del_bins = set(del_cn.index)

        print(row, len(amp_bins), len(del_bins))
        for amp_bin in amp_bins:
            f.write(','.join(map(str, [row['Type'], row['Sample'], source, target, 'Amp', amp_bin, amp_cn.loc[amp_bin]])) + '\n')
            
        for del_bin in del_bins:
            f.write(','.join(map(str, [row['Type'], row['Sample'], source, target, 'Del', del_bin, del_cn.loc[del_bin]])) + '\n')

Type           LUAD
Sample      LUAD01T
Source    LUAD01T_N
Target    LUAD01T_D
Name: 0, dtype: object 2 3
Type            LUAD
Sample       LUAD01T
Source     LUAD01T_N
Target    LUAD01T_LX
Name: 1, dtype: object 1 34
Type            LUAD
Sample       LUAD02T
Source     LUAD02T_N
Target    LUAD02T_LX
Name: 2, dtype: object 0 32
Type           LUAD
Sample      LUAD03T
Source    LUAD03T_N
Target    LUAD03T_A
Name: 3, dtype: object 410 4
Type           LUAD
Sample      LUAD03T
Source    LUAD03T_N
Target    LUAD03T_D
Name: 4, dtype: object 0 4
Type           LUAD
Sample      LUAD03T
Source    LUAD03T_N
Target    LUAD03T_L
Name: 5, dtype: object 0 101
Type            LUAD
Sample       LUAD03T
Source     LUAD03T_N
Target    LUAD03T_LX
Name: 6, dtype: object 0 32
Type            LUAD
Sample       LUAD04T
Source     LUAD04T_N
Target    LUAD04T_A1
Name: 7, dtype: object 464 4
Type           LUAD
Sample      LUAD04T
Source    LUAD04T_N
Target    LUAD04T_D
Name: 8, dtype: object 1 3
Type            LUAD
Sample       LUAD04T
Source     LUAD04T_N
Target    LUAD04T_LX
Name: 9, dtype: object 1 34
Type           LUAD
Sample      LUAD05T
Source    LUAD05T_N
Target    LUAD05T_A
Name: 10, dtype: object 494 0
Type            LUAD
Sample       LUAD05T
Source     LUAD05T_N
Target    LUAD05T_A1
Name: 11, dtype: object 38 71
Type            LUAD
Sample       LUAD05T
Source     LUAD05T_N
Target    LUAD05T_LX
Name: 12, dtype: object 0 33
Type            LUAD
Sample       LUAD05T
Source    LUAD05T_A1
Target    LUAD05T_A2
Name: 13, dtype: object 20 22
Type            LUAD
Sample       LUAD05T
Source    LUAD05T_A1
Target    LUAD05T_A3
Name: 14, dtype: object 46 1
Type            LUAD
Sample       LUAD06T
Source     LUAD06T_N
Target    LUAD06T_A1
Name: 15, dtype: object 305 9
Type            LUAD
Sample       LUAD06T
Source     LUAD06T_N
Target    LUAD06T_A3
Name: 16, dtype: object 13 53
Type            LUAD
Sample       LUAD06T
Source     LUAD06T_N
Target    LUAD06T_LX
Name: 17, dtype: object 1 33
Type            LUAD
Sample       LUAD06T
Source    LUAD06T_A1
Target    LUAD06T_A2
Name: 18, dtype: object 537 0
Type            LUAD
Sample       LUAD07T
Source     LUAD07T_N
Target    LUAD07T_A2
Name: 19, dtype: object 486 0
Type            LUAD
Sample       LUAD07T
Source     LUAD07T_N
Target    LUAD07T_LX
Name: 20, dtype: object 1 33
Type            LUAD
Sample       LUAD07T
Source    LUAD07T_LX
Target    LUAD07T_A2
Name: 21, dtype: object 504 0
Type            LUAD
Sample       LUAD07T
Source    LUAD07T_LX
Target     LUAD07T_L
Name: 22, dtype: object 0 205
Type            LUSC
Sample       LUSC01T
Source     LUSC01T_N
Target    LUSC01T_LX
Name: 23, dtype: object 1 32
Type            LUSC
Sample       LUSC02T
Source     LUSC02T_N
Target    LUSC02T_A1
Name: 24, dtype: object 224 3
Type           LUSC
Sample      LUSC02T
Source    LUSC02T_N
Target    LUSC02T_D
Name: 25, dtype: object 0 3
Type            LUSC
Sample       LUSC04T
Source     LUSC04T_N
Target    LUSC04T_A1
Name: 26, dtype: object 168 17
Type            LUSC
Sample       LUSC04T
Source     LUSC04T_N
Target    LUSC04T_LX
Name: 27, dtype: object 0 32
Type           LUSC
Sample      LUSC05T
Source    LUSC05T_N
Target    LUSC05T_A
Name: 28, dtype: object 409 1
Type            LUSC
Sample       LUSC05T
Source     LUSC05T_N
Target    LUSC05T_L1
Name: 29, dtype: object 2 224
Type            LUSC
Sample       LUSC05T
Source     LUSC05T_N
Target    LUSC05T_LX
Name: 30, dtype: object 1 33
Type           LUSC
Sample      LUSC06T
Source    LUSC06T_N
Target    LUSC06T_A
Name: 31, dtype: object 538 2
Type            LUSC
Sample       LUSC06T
Source     LUSC06T_N
Target    LUSC06T_LX
Name: 32, dtype: object 1 40
Type            LUSC
Sample       LUSC07T
Source     LUSC07T_N
Target    LUSC07T_A1
Name: 33, dtype: object 233 3
Type           LUSC
Sample      LUSC07T
Source    LUSC07T_N
Target    LUSC07T_D
Name: 34, dtype: object 1 4
Type            LUSC
Sample       LUSC07T
Source     LUSC07T_N
Target    LUSC07T_LX
Name: 35, dtype: object 1 17
Type            LUSC
Sample       LUSC07T
Source    LUSC07T_A1
Target    LUSC07T_A3
Name: 36, dtype: object 5 94
Type            LUSC
Sample       LUSC08T
Source     LUSC08T_N
Target    LUSC08T_A1
Name: 37, dtype: object 117 32
Type            LUSC
Sample       LUSC08T
Source     LUSC08T_N
Target    LUSC08T_A2
Name: 38, dtype: object 203 15
Type            LUSC
Sample       LUSC08T
Source     LUSC08T_N
Target    LUSC08T_LX
Name: 39, dtype: object 0 28
Type            LUSC
Sample       LUSC08T
Source    LUSC08T_A2
Target    LUSC08T_A3
Name: 40, dtype: object 60 0
Type            LUSC
Sample       LUSC08T
Source    LUSC08T_A3
Target    LUSC08T_A4
Name: 41, dtype: object 109 0
Type            SCLC
Sample       SCLC01T
Source     SCLC01T_N
Target    SCLC01T_A1
Name: 42, dtype: object 109 11
Type            SCLC
Sample       SCLC01T
Source     SCLC01T_N
Target    SCLC01T_LX
Name: 43, dtype: object 1 32
Type            SCLC
Sample       SCLC01T
Source    SCLC01T_A1
Target    SCLC01T_A2
Name: 44, dtype: object 444 0
Type            SCLC
Sample       SCLC01T
Source    SCLC01T_A1
Target    SCLC01T_A3
Name: 45, dtype: object 0 44
Type           SCLC
Sample      SCLC02T
Source    SCLC02T_N
Target    SCLC02T_A
Name: 46, dtype: object 485 2
Type            SCLC
Sample       SCLC02T
Source     SCLC02T_N
Target    SCLC02T_L1
Name: 47, dtype: object 26 171
Type            SCLC
Sample       SCLC02T
Source     SCLC02T_N
Target    SCLC02T_LX
Name: 48, dtype: object 1 33